### ISSUE TITLE
unable to run the program

### ISSUE THREAD

**Issue by code-rana** [aurotripathy/lstm-anomaly-detect#2]
Hi , 
I tried running this program but got following error : 
`Using TensorFlow backend.
Loading data... 
('wave1', 1000)
('wave2', 1000)
('wave3', 50)
Traceback (most recent call last):
  File "lstm-synthetic-wave-anomaly-detect.py", line 196, in <module>
    run_network()
  File "lstm-synthetic-wave-anomaly-detect.py", line 152, in run_network
    X_train, y_train, X_test, y_test = get_split_prep_data(0, 700, 500, 1000)
  File "lstm-synthetic-wave-anomaly-detect.py", line 70, in get_split_prep_data
    data = gen_wave()
  File "lstm-synthetic-wave-anomaly-detect.py", line 56, in gen_wave
    wave1[insert:insert + 50] = wave1[insert:insert + 50] + wave3
TypeError: slice indices must be integers or None or have an __index__ method`

I did not modify anything , just ran the code as it is yet got this error .
Can you please help what went wrong ?

**Comment by rinkiarya** [comment]
Please replace "wave1[insert:insert + 50] = wave1[insert:insert + 50] + wave3" with 
    "wave1[int(insert):int(insert) + 50] = wave1[int(insert):int(insert) + 50] + wave3". 
Hope this works for you.
Thanks.
